# Generated by Django 4.2.1 on 2023-05-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('hall', models.IntegerField()),
                ('price', models.FloatField()),
                ('seat', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='seats',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
