# Generated by Django 4.2.1 on 2023-05-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_ticket_schedule_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='schedule_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
